# Generated by Django 3.0 on 2023-09-11 08:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='لطفا نام و نام خانوادگی خود را وارد کنید', max_length=35, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(help_text='ایمیل خود را وارد کنید', max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(help_text='لطفا موضوعی برای ارتباط با ما بنویسید', max_length=35, verbose_name='موضوع ارتباط')),
                ('context', models.TextField(help_text='متن مورد نظر خود را وارد کنید', verbose_name='محتوا')),
            ],
            options={
                'verbose_name': 'مخاطب',
                'verbose_name_plural': 'مخاطبان',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(blank=True, choices=[('app', 'اپ'), ('web', 'وبسایت')], help_text='لطفا یک قالب را انتخاب کنید', max_length=10, null=True, verbose_name='قالب پروژه')),
                ('name_project', models.CharField(help_text='لطفا اسم پروژه خود را اضافه کنید', max_length=50, unique=True, verbose_name='نام پروژه')),
                ('image_project', models.ImageField(help_text='لطفا یک تصویر برای پروژه خود انتخاب کنید', upload_to='images_projects', verbose_name='تصویر پروژه')),
                ('description', models.TextField(help_text='درباره پروژه چیزی بنویسید', verbose_name='توضیحات پروژه')),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': 'نمونه کار ها',
                'ordering': ['-name_project'],
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='لطفا مهارت خود را اضافه کنید', max_length=50, unique=True, verbose_name='نام مهارت')),
                ('persent_skill', models.PositiveIntegerField(default=0, help_text='درصد مهارت خود راانتخاب کنید', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد مهارت')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت ها',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network', models.CharField(choices=[('telegram', 'تلگرام'), ('instagram', 'اینستاگرام'), ('linkedin', 'لینکدین'), ('whatsapp', 'واتساپ')], help_text='لطفا شبکه های اجتماعی خود را انتخاب کنید', max_length=10, verbose_name='شبکه های اجتماعی')),
                ('link', models.URLField(help_text='لینک شبکه های خود را وارد کنید', unique=True, verbose_name='لینک شبکه های اجتماعی')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه اجتماعی من',
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='لطفا یک لوگو برای پروژه خود انتخاب کنید', upload_to='image_logo_portfolio', verbose_name='لوگو پروژه')),
                ('title', models.CharField(help_text='لطفا عنوان کیس استادی خود را وارد کنید', max_length=35, verbose_name='عنوان کیس استادی')),
                ('description', models.TextField(help_text='لطفا توضیحات کوتاهی درباره پروژه خود بنویسید', verbose_name='توضیحات پروژه')),
                ('link_case_study', models.URLField(blank=True, help_text='لینک کیس استادی خود را وارد کنید', null=True, unique=True, verbose_name='لینک کیس استادی')),
                ('portfolio', models.OneToOneField(help_text='لطفا یک کیس استادی برای نمونه کار های خود انتخاب کنید', on_delete=django.db.models.deletion.CASCADE, to='resume.Portfolio', verbose_name='کیس استادی نمونه کار')),
            ],
            options={
                'verbose_name': ' کیس استادی',
                'verbose_name_plural': 'کیس استادی های نمونه کار ها',
            },
        ),
    ]
